### ISSUE TITLE
Ollama not installing on the Mac Intel x64 

### ISSUE THREAD

**Issue by betterbrand** [BruceMacD/chatd#17]
Using ARM, everything works as expected.  Without Ollama installed, the app functions perfectly.

Using electron-forge, I've added an x64 dmg build.  Electron builds, notarizes, staples, and installs on Mac intel machines.

I have ollama included in the package at `src/service/ollama/runners/ollama-darwin.app`
When people test the app, an error is thrown:

![Signal (7) 2023-11-30 11-28-11](https://github.com/BruceMacD/chatd/assets/76454555/5ac911fb-d2cf-4238-83fe-1c7bd37b909c)

I've tried to put the ollama.app in a directory called 'ollama-darwin' like this:  `src/service/ollama/runners/ollama-darwin/ollama.app`, but still got the error.

Thanks in advance for your help.  I love this project.

**Comment by BruceMacD** [comment]
Hey @betterbrand thanks for the kind words. `ollama-darwin` is actually what the executable is named rather than a directory it should be in. I see the confusion here, I'll fix the README now.

For reference, here are the steps re-worded for clarity.
1. Download `ollama-darwin` from [ollama-darwin](https://github.com/jmorganca/ollama/releases/download/v0.1.13/ollama-darwin)
2. Make the downloaded binary executable: `chmod +x /path/to/ollama-darwin`
3. Place this `ollama-darwin` executable directly into `src/service/ollama/runners` (not a sub-directory).

Let me know if you hit anymore issues.

**Comment by BruceMacD** [comment]
Resolved in [6005f39](https://github.com/BruceMacD/chatd/commit/6005f3901e5e565cfd055b9d7e0b9188fd209910)
